### ISSUE TITLE
DockerHub

### ISSUE THREAD

**Issue by nknowlton** [GenomicsAotearoa/bioinformatics-containers#1]
Can this GA repository be auto-built on DockerHub.  Singularity is easist on our end when pulling in built docker containers.

**Comment by kiwiroy** [comment]
Why not [singularity hub](https://www.singularity-hub.org)?

**Comment by nknowlton** [comment]
I think singularity hub is dead.  I have some projects at [syslab-cloud](https://cloud.sylabs.io/builder), but    I haven't figured out how to directly use Dockerfile recipes there. For maintainability, this project is docker focused and singularity is only needed on one compute node currently.

**Comment by kiwiroy** [comment]
Certainly in a transition stage...

**Comment by nknowlton** [comment]
@mikblack  Can you set this up?

**Comment by jduckles** [comment]
Anyone can create a Docker Hub organisation, just make sure you make @mikblack an owner of it (he may have to sign up too). We've got https://hub.docker.com/u/gacancergenomics if you'd like to use that, just flick me your dockerhub usernames by email and I'll add you to the org. 

Edit: Fixed the link

**Comment by nknowlton** [comment]
I was trying to link the auto-build to git commits on a GA project.  Docker Hub said GA needed to allow this connection, so I thought @mikblack  needed to enable this.

**Comment by nknowlton** [comment]
I've set this up @ docker://nknowlton/bioinformatics-containers.
